### ISSUE TITLE
Adding audio playback to Soundcloud page on mobile

### ISSUE THREAD

**Issue by jlooper** [jlooper/pocketrave-rc4#7]
I'm getting an error: 

`file:///app/tns_modules/@angular/core/src/reflection/reflection_capabilities.js:91:136: JS ERROR Error: Cannot create a factory for 'TNSPlayer' because its constructor has more than 20 arguments`

when trying to enable the nativescript-audio plugin. I only need to play remote files from Soundcloud on the native app. Wondering what I'm doing wrong? The files in question are in the /soundcloud folder, only for mobile.

**Comment by NathanWalker** [comment]
Everything looked right here at first glance, haven't run it yet (will do later).
Maybe just needs a clean run?
Go into nativescript folder....
```
cd nativescript
rm -rf node_modules lib hooks platforms
tns emulate ios
```
I'll be back later to look more.

**Comment by jlooper** [comment]
entirely unable to rebuild :D fun times! 
@angular/core@2.0.0-rc.4 seems to be throwing an error: 
`Unable to install dependencies. Make sure your package.json is valid and all dependencies are correct. Error is: The package @angular/core@2.0.0-rc.4 does not satisfy its siblings' peerDependencies requirements!`

**Comment by jlooper** [comment]
going to close this as it's a different story for RC5
